sites/main/views.py
from flask import render_template, request, Blueprint

from sites import provide_user, require_session_token

blueprint = Blueprint("main", __name__, url_prefix="/", static_folder="../../static")

@blueprint.route('/', methods=["GET"])
@provide_user
def index():
    return render_template("index.html", user=request.user)

@blueprint.route('/about', methods=["GET"])
@provide_user
def about():
    return render_template("about.html", user=request.user, active4="active")

@blueprint.route('/js-example', methods=["GET"])
def jsexample():
    return render_template("js-example.html")

@blueprint.route('/js-example2', methods=["GET"])
def jsexample2():
    return render_template("js-example2.html")

@blueprint.route('/faq', methods=["GET"])
@require_session_token
def faq():
    return render_template("faq.html", user=request.user, active3="active")

sites/user/__init__.py
import sites.user.views

sites/user/views.py
import base64
import datetime
import logging
import uuid

from flask import render_template, request, make_response, redirect, url_for, flash, Blueprint
from flask_mail import Message

from extensions import db, mail, bcrypt
from model import User
from sites import provide_user, WEBSITE_LOGIN_COOKIE_NAME, SENDER, HOST_ADDR, check_email, COOKIE_DURATION, \
    require_session_token

blueprint = Blueprint("user", __name__, url_prefix="/users", static_folder="../../static")

@blueprint.route('/login', methods=["GET", "POST"])
@provide_user
def login():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        # right way to find user with correct password
        user = User.query \
            .filter(User.username == username) \
            .first()

        session_cookie = str(uuid.uuid4())
        expiry_time = datetime.datetime.now() + datetime.timedelta(seconds=COOKIE_DURATION)

        redirect_url = request.args.get('redirectTo', url_for('main.index'))

        if user is None:
            flash("Username or password is wrong", "warning")
            logging.info(f"User {username} failed to login with wrong username or password.") # But username
            redirect_url = request.args.get('redirectTo', url_for('main.index'))
            return redirect(url_for('user.login', redirectTo=redirect_url))
        elif not bcrypt.check_password_hash(user.password_hash, password):
            flash("Username or password is wrong", "warning")
            logging.info(f"User {username} failed to login with wrong username or password.") # But actually password

            return redirect(url_for('user.login', redirectTo=redirect_url))
        else:
            user.session_cookie = session_cookie
            user.session_expiry_datetime = expiry_time
            db.session.add(user)
            db.session.commit()
            logging.info(f"User {username} is logged in")

        redirect_url = request.args.get('redirectTo', url_for('main.index'))
        response = make_response(redirect(redirect_url))
        response.set_cookie(WEBSITE_LOGIN_COOKIE_NAME, session_cookie, httponly=True, samesite='Strict')
        return response

    elif request.method == "GET":
        cookie = request.cookies.get(WEBSITE_LOGIN_COOKIE_NAME)
        user = None

        if cookie is not None:
            user = User.query \
                .filter_by(session_cookie=cookie) \
                .filter(User.session_expiry_datetime >= datetime.datetime.now()) \
                .first()

        if user is None:
            logged_in = False
        else:
            logged_in = True

        return render_template("login.html", logged_in=logged_in, user=request.user)


@blueprint.route("/registration", methods=["GET", "POST"])
@provide_user
def registration():
    if request.method == "POST":
        username = request.form.get("username")
        email = request.form.get("email")
        password = request.form.get("password")
        repeat = request.form.get("repeat")

        # check email valid
        is_valid = check_email(email)
        if not is_valid:
            flash("Email is not a valid email", "warning")
            return redirect(url_for("user.registration"))

        if password != repeat:
            flash("Password and repeat did not match!", "warning")
            return redirect(url_for("user.registration"))

        # check if email is already taken:
        user = User.query.filter_by(email=email).first()
        if user:
            flash("Email is already taken", "warning")
            return redirect(url_for("user.registration"))

        # check if username is already taken in Database!
        user = User.query.filter_by(username=username).first()
        if user:
            flash("Username is already taken", "warning")
            return redirect(url_for('user.registration'))

        password_hash = bcrypt.generate_password_hash(password).decode('utf-8')
        session_cookie = str(uuid.uuid4())

        session_expiry_datetime = datetime.datetime.now() + datetime.timedelta(seconds=COOKIE_DURATION)

        user = User(username=username,
                    email=email,
                    password_hash=password_hash,
                    session_cookie=session_cookie,
                    session_expiry_datetime=session_expiry_datetime)
        db.session.add(user)
        db.session.commit()
        flash("Registration Successful!", "success")

        # send registration confirmation email
        msg = Message(
            subject="WebDev Blog - Registration Successful",
            sender=SENDER,
            recipients=[email],
            bcc=[SENDER]
        )
        msg.body = f"Hi {username}!\n" \
                   f"Welcome to our WebDev Flask site!\n" \
                   f"Visit us: {HOST_ADDR}\n" \
                   f"Enjoy!"
        mail.send(msg)

        # set cookie for the browser
        response = make_response(redirect(url_for('main.index')))
        response.set_cookie(WEBSITE_LOGIN_COOKIE_NAME, session_cookie, httponly=True, samesite='Strict')
        return response

    elif request.method == "GET":
        return render_template("registration.html", user=request.user, active0="active")


@blueprint.route('/profiles/<username>', methods=["GET", "POST"])
@require_session_token
def profile(username):
    user = User.query.filter_by(username=username).one()
    if request.method == "POST":
        email = request.form.get("email")
        if email != user.email:
            user.email = email

        hobby = request.form.get("hobby")
        if hobby != user.hobby:
            user.hobby = hobby

        profilepic = request.files.get("profilepic")
        if profilepic != user.profilepic:
            user.profilepic = profilepic.stream.read()

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('user.profile', username=username))

    elif request.method == "GET":
        profilepic_base64 = base64.encodebytes(user.profilepic or b"").decode('ascii')

        return render_template("profile.html", user=user, profilepic_base64=profilepic_base64)


@blueprint.route('/users', methods=["GET"])
@require_session_token
def users():
    current_user = request.user

    if request.method == "GET":
        allusers = User.query.all()
        return render_template("users.html", users=allusers, user=request.user, active2="active")

@blueprint.route('/logout', methods=["GET"])
@provide_user
def logout():
    response = make_response(redirect(url_for('main.index')))
    response.set_cookie(WEBSITE_LOGIN_COOKIE_NAME, expires=0)

    user = User.query \
        .filter_by(username=request.user.username) \
        .first()

    if user is not None:
        # reset user
        user.session_expiry_datetime = None
        user.session_cookie = None
        db.session.add(user)
        db.session.commit()
        logging.info(f"{user.username} has logged out.")

    return response

templates/about.html
{% extends "frame.html" %}

{% block title %}
About
{% endblock title %}

{% block content %}

<div class="row">
    <div class="col-md-12 text-center">
        <h2>About</h2>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <img src= {{ url_for('static', filename = 'images/abstract.jpg') }} alt="Abstract image" title="Mlog abstract image" class="img-fluid rounded-lg">
    </div>
    <div class="col-md-9">
        <p>
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus.
        </p>
        <p>
            Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt.
        </p>
    </div>
</div>
{% endblock content %}

templates/csrf_error.html
{% extends "frame.html" %}

{% block title %}
    404: Page Not Found
{% endblock title %}

{% block navigation %}

{% include "components/navigation.html" %}

{% endblock navigation %}

{% block content %}
    <h1 class="text-center"><span class="badge badge-pill badge-warning p-4 my-4">CSRF Error<br>Security issue</span></h1>
{% endblock content %}

templates/faq.html
{% extends "frame.html" %}

{% block title %}
FAQ
{% endblock title %}

{% block content %}

<div class="row">
    <div class="col-md-12 text-center">
        <h2>FAQ</h2>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <div class="accordion shadow" id="accordionExample">
            <div class="card">
                <div class="card-header" id="headingOne">
                    <h2 class="mb-0">
                        <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse"
                                data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit?
                        </button>
                    </h2>
                </div>

                <div id="collapseOne" class="collapse show" aria-labelledby="headingOne"
                     data-parent="#accordionExample">
                    <div class="card-body">
                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.
                        3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt
                        laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin
                        coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes
                        anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings
                        occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard
                        of them accusamus labore sustainable VHS.
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header" id="headingTwo">
                    <h2 class="mb-0">
                        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse"
                                data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            Aenean commodo ligula eget dolor?
                        </button>
                    </h2>
                </div>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                    <div class="card-body">
                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.
                        3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt
                        laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin
                        coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes
                        anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings
                        occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard
                        of them accusamus labore sustainable VHS.
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header" id="headingThree">
                    <h2 class="mb-0">
                        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse"
                                data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                            Cum sociis natoque penatibus et magnis dis parturient montes?
                        </button>
                    </h2>
                </div>
                <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                    <div class="card-body">
                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.
                        3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt
                        laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin
                        coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes
                        anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings
                        occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard
                        of them accusamus labore sustainable VHS.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <img src= {{ url_for('static', filename = 'images/abstract2.jpg') }} alt="Abstract image" title="Mlog abstract image" class="img-fluid rounded-lg">
    </div>
</div>
{% endblock content %}

templates/footer.html
<div class="container-fluid text-center mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3 text-center mt-5">
            <div class="alert alert-success" role="alert">
                This is an exercise project in a course by <a href="http://smartninja.org" target="_blank">SmartNinja</a><br>
                    Please find the <a href="https://github.com/mbalabanov/webdev2-heroku-flask" target="_blank">code repository on Github.</a>
            </div>
        </div>
    </div>
</div>

<footer class="py-5 bg-dark text-light">
    <div class="container text-center">
        <img src= {{ url_for('static', filename = 'images/blogo.png') }} alt="MLOG Logo" title="MLOG Logo" height="120" class="my-2">
        <p class="m-4">Site Designed by Marin Balabanov.<br>Images from Adobe Stock.</p>
    </div>
</footer>

templates/frame.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    {% block css %}
    {% endblock css %}

</head>
<body>

{% include 'navigation.html' %}

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                <span>{{ message }}</span>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

<!-- Main content -->
<div class="container my-4">
{% block content %}
{% endblock content %}
</div>

{% include 'footer.html' %}

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

</body>
</html>

templates/index.html
{% extends "frame.html" %}

{% block title %}
Home
{% endblock title %}

{% block content %}

<div class="row">
    <div class="col-md-12 text-center">
        <h2>Welcome to this Exercise Project</h2>
        <img src= {{ url_for('static', filename = 'images/header-decoration1.jpg') }} alt="Abstract image" title="Mlog abstract image" class="img-fluid rounded-lg my-2">
    </div>
</div>

<div class="row mt-4">
    <div class="col-md-4">
        <div class="text-center border rounded-lg p-4 m-2">
            <a href="/login"><img src={{ url_for('static', filename = 'images/square1.jpg') }} alt="First abstract square" title="Mlog abstract square" class="img-fluid rounded-lg"></a>
            <h4><a href="/login">Register a User Account</a></h4>
            <p>Please register a user account and then login.</p>
            <a class="btn btn-primary btn-sm" href="/login">Register</a>
        </div>
    </div>
    <div class="col-md-4">
        <div class="text-center border rounded-lg p-4 m-2">
            <a href="/blog"><img src= {{ url_for('static', filename = 'images/square2.jpg') }} alt="Second abstract square" title="Mlog abstract square" class="img-fluid rounded-lg"></a>
            <h4><a href="/blog">View or Write a Blog Post</a></h4>
            <p>Read the blog posts, comment on them or write your own.</p>
            <a class="btn btn-primary btn-sm" href="/blog">Blog</a>
        </div>
    </div>
    <div class="col-md-4">
        <div class="text-center border rounded-lg p-4 m-2">
            <a href="https://github.com/mbalabanov/webdev2-heroku-flask" target="_blank"><img src= {{ url_for('static', filename = 'images/square3.jpg') }} alt="First abstract square" title="Mlog abstract square" class="img-fluid rounded-lg"></a>
            <h4><a href="https://github.com/mbalabanov/webdev2-heroku-flask" target="_blank">Learn More about the Project</a></h4>
            <p>Read the blog posts, comment on them or write your own.</p>
            <a class="btn btn-primary btn-sm" href="https://github.com/mbalabanov/webdev2-heroku-flask" target="_blank">Github</a>
        </div>
    </div>
</div>

{% endblock content %}

templates/js-example.html
{% extends "frame.html" %}

{% block title %}
FAQ
{% endblock title %}

{% block content %}

<div class="row">
    <div class="col-md-12 text-center">
        <h2>FAQ</h2>
    </div>
</div>

<div class="row">
    <div class="col-md-8 offset-md-2">

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Coin</th>
                    <th>Exchange Rate (EURO)</th>
                </tr>
            </thead>
            <tbody>
                <td style="min-width: 150px;">
                    <select id="coinSelector" name="coin_symbol" style="min-width: 150px; width:100%" onchange="change_coin();">
                        <option value="" disabled selected>Select your Coin</option>
                        <option id="BTC" value="BTC"> Bitcoin (BTC)</option>
                        <option id="ETH" value="ETH"> Ethereum (ETH)</option>
                        <option id="XLM" value="XLM"> Lumen (XLM)</option>
                    </select>
                </td>
                <td id="selectedCoinExchangeRate"></td>
            </tbody>
        </table>

        <script type="text/javascript" src="static/js/coincalc.js"></script>

    </div>
</div>
{% endblock content %}

templates/login.html
{% extends "frame.html" %}

{% block title %}
Login
{% endblock title %}

    {% block content %}

        <div class="row">
            <div class="col-md-12 text-center">
                <h2>Login</h2>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 offset-md-4">

                {% if not logged_in %}

                <form name="loginForm" onsubmit="return validateLoginForm()" method="post">
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="text" name="username" class="form-control" id="username" aria-describedby="usernameHelp">
                        <p id="username-message"></p>
                    </div>

                    <div class="form-group">
                        <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
                    </div>

                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" class="form-control" id="password">
                        <p id="password-message"></p>
                    </div>
                    <button type="submit" class="btn btn-primary">Login</button>
                </form>

                {% else %}

                <h1>You are logged in!</h1>

                {% endif %}

            </div>
        </div>

        <script type="text/javascript" src="../static/js/logincheck.js"></script>

    {% endblock content %}

templates/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color: #e3f2fd;">
    <a href="/"><img src= {{ url_for('static', filename = 'images/blogo.png') }} alt="Mlog Logo" title="Logo of Mlog" width="50px" class="mx-4"></a>
    <a class="navbar-brand" href="{{url_for('main.index')}}">MBLOG</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {{active1}}">
                <a class="nav-link" href="{{url_for('blog.posts')}}">Blog</a>
            </li>
            <li class="nav-item {{active2}}">
                <a class="nav-link" href="{{url_for('user.users')}}">Users</a>
            </li>
            <li class="nav-item {{active3}}">
                <a class="nav-link" href="{{url_for('main.faq')}}">FAQ</a>
            </li>
            <li class="nav-item {{active4}}">
                <a class="nav-link" href="{{url_for('main.about')}}">About</a>
            </li>
            {% if not user %}
            <li class="nav-item {{active0}}">
                <a class="nav-link" href="{{url_for('user.registration')}}">Register</a>
            </li>
            {% endif %}

        </ul>

        {% if user %}

            <a class="text-white mr-2" href="{{url_for('user.profile', username=user.username)}}">User: {{user.username}}</a>
            <a class="btn btn-light mr-2" role="button" href="{{url_for('user.logout')}}">Logout</a>

        {% else %}

            <a class="btn btn-primary mx-2" href="{{url_for('user.login')}}">Login</a>

        {% endif %}

        <form class="form-inline my-2 my-lg-0 mr-2">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

templates/new_comment.html
<h2>Hello there!</h2>

<p>A new comment was added to:</p>
<a href="/posts/{{post.id}}">{{post.title}}</a>

templates/new_post.html
<h2>Hello {{username}}</h2>

<p>There is news, check this out:</p>
<a href="{{link}}">{{post.title}}</a>

<p>Best wishes!</p>

templates/post.html
{% extends "frame.html" %}

{% block title %}
Posts - {{post.title}}
{% endblock title %}

{% block content %}

<div class="row mt-4 text-center">
    <div class="col-md-12">
        <h2>Post Details</h2>
    </div>
</div>

<div class="row mt-4">
    <div class="col-md-10 offset-md-1">
        <h3 class="display-4">{{post.title}}</h3>
        <p><em>{{post.created}}</em></p>
        <p>Written by <span class="badge badge-secondary p-2">{{post.user.username}}</span></p>
        <p class="lead">{{post.text}}</p>

        {% if comments %}
            <h4>Comments</h4>
        {% else %}
        <div class="alert alert-secondary" role="alert">
            <h2>No Comments</h2>
        </div>
        {% endif %}

        {% for comment in comments %}
        <div class="alert alert-secondary" role="alert">
            <p>{{comment.text}}</p>
            <hr class="my-1">
            <p><sup>Written by <strong>{{comment.user.username}}</strong> on {{comment.created}}</sup></p>
        </div>
        {% endfor %}
    </div>
</div>

<div class="row mt-5">
    <div class="col-6 offset-3">
        <div class="alert alert-primary" role="alert">
            <form id="commentForm" onsubmit="return validateCommentForm()" method="post">
                <div class="form-group">
                    <label for="commentInput">Write a Comment</label>
                    <input type="text" name="text" class="form-control" placeholder="Your comment..." id="commentInput">
                    <p id="message0"></p>
                </div>
                <div class="form-group">
                    <input type="text" hidden name="csrf_token"  class="form-control" id="csrf_token" value="{{csrf_token}}">
                </div>
                <button type="submit" class="btn btn-primary">Send</button>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript" src="{{ url_for('static', filename = 'js/commentcheck.js') }}"></script>

{% endblock content %}

templates/posts.html
{% extends "frame.html" %}

{% block title %}
Blog
{% endblock title %}

{% block content %}

<div class="row">
    <div class="col-md-12 text-center">
        <h2>Blog</h2>
    </div>
</div>

{% for post in posts %}

<div class="row my-4">
    <div class="div-md-10 offset-md-1">
        <h3 class="display-4"><a href="{{url_for('blog.post', post_id=post.id)}}">{{post.title}}</a></h3>
        <p><em>{{post.created}}</em></p>
        <p>Written by <span class="badge badge-secondary p-2">{{post.user.username}}</span></p>
        <p class="lead">{{post.text}}</p>
        <a class="btn btn-primary" href="/posts/{{post.id}}" role="button">Read more</a>
        <hr class="my-4">
    </div>
</div>

{% endfor %}


<div class="row">
    <div class="col-8 offset-2">
        <div class="alert alert-primary" role="alert">
            <h4>Write a new Blog Post</h4>
            <form id="postForm" onsubmit="return validatePostForm()" method="post">
                <div class="form-group">
                    <label for="posttitle">Post Title</label>
                    <input type="text" name="posttitle" class="form-control" id="posttitle">
                    <p id="message0"></p>
                </div>
                <div class="form-group">
                    <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
                </div>
                <div class="form-group">
                    <label for="posttest">Post Content</label>
                    <textarea rows="6" name="posttext" class="form-control" id="posttest"></textarea>
                    <p id="message1"></p>
                </div>
                <button type="submit" class="btn btn-primary">Post</button>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript" src="../static/js/postcheck.js"></script>

{% endblock content %}

templates/users.html
{% extends "frame.html" %}

{% block title %}
Users
{% endblock title %}

{% block content %}

<div class="row">
    <div class="col-md-12 text-center">
        <h2>Users</h2>
    </div>
</div>

<div class="row mt-4">
    <div class="col-md-12">

        <table class="table table-bordered shadow">
          <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Username</th>
                <th scope="col">Email Address</th>
                <th scope="col">Created On</th>
                <th scope="col">Updated On</th>
                <th scope="col">User Role</th>
            </tr>
          </thead>
          <tbody>

            {% for user in users %}

            <tr>
                <td>{{user.id}}</td>
                <td>{{user.username}}</td>
                <td>{{user.email}}</td>
                <td>{{user.created}}</td>
                <td>{{user.updated}}</td>
                <td>{{user.role}}</td>
            </tr>

            {% endfor %}

          </tbody>
        </table>

    </div>
</div>
{% endblock content %}